apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    app: istio-ingress
    istio: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istio-ingress
      istio: ingress
  template:
    metadata:
      labels:
        app: istio-ingress
        istio: ingress
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-ingress
      containers:
      - name: istio-proxy
        image: istio/proxyv2:1.20.0
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 15090
          name: prometheus
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
