apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml

namespace: istio-system

commonLabels:
  app: istio-ingress
  istio: ingress
