apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: istio-system
  labels:
    app: istio-ingress
    istio: ingress
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  - name: http-envoy-prom
    port: 15090
    targetPort: 15090
  selector:
    app: istio-ingress
    istio: ingress
