apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sample-apps
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: backend
        image: nginx:alpine
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "http://database:5432"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache curl
          while true; do
            echo "Backend calling database..."
            curl -s $DATABASE_URL/health || echo "Database call failed"
            sleep 3
          done
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sample-apps
  labels:
    app: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: backend
