apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: sample-apps
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: database
        image: nginx:alpine
        ports:
        - containerPort: 5432
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache curl
          while true; do
            echo "Database is running..."
            sleep 10
          done
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: sample-apps
  labels:
    app: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: database

