apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sample-apps
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://backend:8080"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          apk add --no-cache curl
          while true; do
            echo "Frontend calling backend..."
            curl -s $BACKEND_URL/api/hello || echo "Backend call failed"
            sleep 5
          done
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sample-apps
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend

