apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-discovery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.20.0
    helm:
      values: |
        # Istio control plane configuration
        global:
          # Enable mTLS by default
          mtls:
            enabled: true
          # Enable auto-injection
          proxy:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi
        pilot:
          # Enable automatic sidecar injection
          autoscaleEnabled: true
          autoscaleMin: 1
          autoscaleMax: 3
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
            limits:
              cpu: 1000m
              memory: 4096Mi
          # Explicitly control sidecar injection
          enableNamespacesByDefault: false
          # Exclude istio-system namespace from injection
          excludeNamespaces:
            - istio-system
            - kube-system
            - argocd
        telemetry:
          # Enable telemetry collection
          enabled: true
        tracing:
          # Enable Jaeger integration
          enabled: true
          provider: jaeger
        # Additional injection control
        sidecarInjectorWebhook:
          # Disable injection for istio-system namespace
          namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - istio-system
                  - kube-system
                  - argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
