apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.26.3
    helm:
      values: |
        # Gateway configuration
        service:
          type: ClusterIP  # Only ClusterIP - ALB will handle external access
          ports:
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
        
        # Pod configuration
        podAnnotations:
          sidecar.istio.io/inject: "false"  # Disable sidecar injection for the gateway itself
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        # Security context
        securityContext:
          sysctls:
            - name: net.ipv4.ip_unprivileged_port_start
              value: "0"
        
        # Service account
        serviceAccount:
          create: true
          name: istio-ingressgateway
        
        # Labels to match our gateway selector
        labels:
          istio: ingressgateway
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
