apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.16.11
    helm:
      values: |
        # Linkerd configuration with proper auto-certificate generation
        global:
          clusterDomain: cluster.local
        # This enables automatic certificate generation
        identity:
          issuer:
            scheme: kubernetes.io/tls
        # Resource limits for components
        proxy:
          resources:
            cpu:
              request: 10m
              limit: 100m
            memory:
              request: 20Mi
              limit: 250Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
