apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: traffic-generator
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            echo "Generating traffic to ArgoCD..."
            curl -s http://argocd-server.argocd.svc.cluster.local:80 || echo "ArgoCD call failed"
            
            echo "Generating traffic to Prometheus..."
            curl -s http://prometheus-server.monitor.svc.cluster.local:80/api/v1/query?query=up || echo "Prometheus call failed"
            
            echo "Generating traffic to Kiali..."
            curl -s http://kiali.istio-system.svc.cluster.local:20001 || echo "Kiali call failed"
            
            echo "Generating traffic to Traefik..."
            curl -s http://traefik.traefik.svc.cluster.local:80 || echo "Traefik call failed"
            
            echo "Generating traffic to Istio..."
            curl -s http://istiod.istio-system.svc.cluster.local:15014/version || echo "Istio call failed"
            
            echo "Waiting 10 seconds before next round..."
            sleep 10
          done
