apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: traffic-generator
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          while true; do
            echo "Generating traffic to ArgoCD..."
            curl -s http://argocd-server.argocd.svc.cluster.local:80 || echo "ArgoCD call failed"
            
            echo "Generating traffic to Prometheus..."
            curl -s http://prometheus-server.monitor.svc.cluster.local:80/api/v1/query?query=up || echo "Prometheus call failed"
            
            echo "Generating traffic to Kiali..."
            curl -s http://kiali.kiali.svc.cluster.local:20001 || echo "Kiali call failed"
            
            echo "Generating traffic to Traefik..."
            curl -s http://traefik.traefik.svc.cluster.local:80 || echo "Traefik call failed"
            
            echo "Generating traffic to sample apps..."
            curl -s http://frontend.sample-apps.svc.cluster.local:80 || echo "Frontend call failed"
            curl -s http://backend.sample-apps.svc.cluster.local:8080 || echo "Backend call failed"
            curl -s http://database.sample-apps.svc.cluster.local:5432 || echo "Database call failed"
            
            echo "Waiting 15 seconds before next round..."
            sleep 15
          done
